### ISSUE TITLE
Providers.ofが非推奨となっておりproviderに書き換えた場合の書き方がわからない。

### ISSUE THREAD

**Issue by RN24Nishioka** [RN24Nishioka/Android-practice#1]
## 環境
Android Studio 4.0.1
Build #AI-193.6911.18.40.6626763, built on June 25, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.new.welcome.screen.force=true, debugger.watches.in.variables=false
Non-Bundled Plugins: Dart, com.google.services.firebase, com.intellij.marketplace, com.thoughtworks.gauge, io.flutter, org.intellij.plugins.markdown

## 質問の概要

[この動画](https://www.youtube.com/watch?v=n4ZiNXMn34k&list=PLL-4P1BOZnWyGo-7VP5YuB4qa94T0M_4v&index=33)を見て学習。
[動画のソースコード](https://github.com/LEMUBIT/CybraryShoppingApp/blob/master/app/src/main/java/com/lemubit/lemuel/cybraryshoppingapp/MainActivity.java#L41)

ViewModelProviders.ofが非推奨となっており色々見ながら
[このmainActivityViewModel = new ViewModelProvider(this).get(MainActivityViewModel.class);](https://github.com/RN24Nishioka/Android-practice/blob/master/app/src/main/java/com/example/cybaryhelloapp/MainActivity.java#L43)
ように修正したが下記のようなエラーが出て動かない。

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.cybaryhelloapp, PID: 21237
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.cybaryhelloapp/com.example.cybaryhelloapp.MainActivity}: java.lang.RuntimeException: Cannot create an instance of class com.example.cybaryhelloapp.MainActivityViewModel
```

## 参考にした記事など

https://developer.android.com/reference/androidx/lifecycle/ViewModelProviders#public-methods
https://stackoverflow.com/questions/60332845/viewmodelproviders-is-deprecated-in-2-2-0
https://www.youtube.com/watch?v=wjG4VQ3x7xE&t=124s

## デバッグ内容と自身の考察

非推奨となったViewModelProviders.ofからViewModelProviderの書き方に書き換えないと行けないようだが色々とサイトをみて試したが動かないまま。書き方がわかれば動くようになるのではと考えるがうまく出来ない・・・。

以下エラー全文

```
08/15 12:37:16: Launching 'app' on Nexus 5X API 28.
$ adb shell am start -n "com.example.cybaryhelloapp/com.example.cybaryhelloapp.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Waiting for application to come online: com.example.cybaryhelloapp.test | com.example.cybaryhelloapp
Waiting for application to come online: com.example.cybaryhelloapp.test | com.example.cybaryhelloapp
Connected to process 21237 on device 'Nexus_5X_API_28 [emulator-5554]'.
Waiting for application to come online: com.example.cybaryhelloapp.test | com.example.cybaryhelloapp
Connecting to com.example.cybaryhelloapp
Connected to the target VM, address: 'localhost:8629', transport: 'socket'
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/.cybaryhelloap: Not late-enabling -Xcheck:jni (already on)
W/.cybaryhelloap: Unexpected CPU variant for X86 using defaults: x86
W/ActivityThread: Application com.example.cybaryhelloapp is waiting for the debugger on port 8100...
I/System.out: Sending WAIT chunk
I/System.out: Debugger has connected
I/System.out: waiting for debugger to settle...
I/chatty: uid=10101(com.example.cybaryhelloapp) identical 2 lines
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/chatty: uid=10101(com.example.cybaryhelloapp) identical 3 lines
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1430)
W/.cybaryhelloap: Accessing hidden method Landroid/graphics/drawable/Drawable;->getOpticalInsets()Landroid/graphics/Insets; (light greylist, linking)
    Accessing hidden field Landroid/graphics/Insets;->left:I (light greylist, linking)
    Accessing hidden field Landroid/graphics/Insets;->right:I (light greylist, linking)
    Accessing hidden field Landroid/graphics/Insets;->top:I (light greylist, linking)
    Accessing hidden field Landroid/graphics/Insets;->bottom:I (light greylist, linking)
W/.cybaryhelloap: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
W/.cybaryhelloap: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
W/.cybaryhelloap: Accessing hidden method Landroid/widget/TextView;->getTextDirectionHeuristic()Landroid/text/TextDirectionHeuristic; (light greylist, linking)
W/.cybaryhelloap: Accessing hidden method Landroid/widget/PopupWindow;->setEpicenterBounds(Landroid/graphics/Rect;)V (light greylist, linking)
W/.cybaryhelloap: Accessing hidden method Landroid/widget/PopupWindow;->setClipToScreenEnabled(Z)V (light greylist, reflection)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.cybaryhelloapp, PID: 21237
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.cybaryhelloapp/com.example.cybaryhelloapp.MainActivity}: java.lang.RuntimeException: Cannot create an instance of class com.example.cybaryhelloapp.MainActivityViewModel
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.RuntimeException: Cannot create an instance of class com.example.cybaryhelloapp.MainActivityViewModel
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:271)
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:106)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at com.example.cybaryhelloapp.MainActivity.onCreate(MainActivity.java:43)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.IllegalAccessException: java.lang.Class<com.example.cybaryhelloapp.MainActivityViewModel> is not accessible from java.lang.Class<androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory>
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:267)
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:106) 
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185) 
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150) 
        at com.example.cybaryhelloapp.MainActivity.onCreate(MainActivity.java:43) 
        at android.app.Activity.performCreate(Activity.java:7136) 
        at android.app.Activity.performCreate(Activity.java:7127) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
I/Process: Sending signal. PID: 21237 SIG: 9
Disconnected from the target VM, address: 'localhost:8629', transport: 'socket'

```

**Comment by RN24Nishioka** [comment]
下記のようにアドバイスを頂き解決しました。クローズします。

ViewModelのコンストラクタに引数があるときは、ViewModelProviderのコンストラクタ第2引数にViewModelProvider.Factoryのインスタンスを渡します。
```
        mainActivityViewModel = new ViewModelProvider(this, new ViewModelProvider.Factory(){
            @NonNull
            @Override
            public <T extends ViewModel> T create(@NonNull Class<T> modelClass) {
                //noinspection unchecked
                return (T) new MainActivityViewModel(getApplication());
            }
        }).get(MainActivityViewModel.class);
```
